version: "3.9"
services:
  app:
    build: .
    entrypoint: 
    - /project/entrypoint.sh
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
    - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

